services:
  mysql:
    image: mysql:8.0
    container_name: prj-mysql
    environment:
      MYSQL_DATABASE: prj_entrades
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - prj-network

  backend-api:
    build:
      context: ./src/backend-api
    container_name: prj-backend-api
    volumes:
      - ./src/backend-api:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - prj-network

  backend-ws:
    image: node:24
    container_name: prj-backend-ws
    volumes:
      - ./src/backend-ws:/app
    working_dir: /app
    depends_on:
      - mysql
    command: sh -c "npm install && node server.js"
    ports:
      - "4000:4000"
    networks:
      - prj-network

  frontend:
    image: node:24
    container_name: prj-frontend
    volumes:
      - ./src/frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: sh -c "npm install && npm run dev"
    networks:
      - prj-network

  adminer:
    image: adminer:4.8.1
    container_name: prj-adminer
    user: root
    ports:
      - "8088:8080"
    networks:
      - prj-network

networks:
  prj-network:
    driver: bridge
